const glossary=[
['punctual','ملتزم بالمواعيد'],['polite','مُهذّب'],['active listening','الإصغاء الفعّال'],['eye contact','التواصل البصري'],['posture','وضعية الجسم'],['gesture','إيماءة'],['self-correct','يُصحّح نفسه'],['follow-up question','سؤال متابعة'],['currently','حاليًا'],['graduate from','يتخرّج من'],['experience','خبرة / تجربة'],['strategy','استراتيجية / طريقة'],['prioritize','يُحدّد الأولويات'],['deadline','موعد نهائي'],['reliable source','مصدر موثوق'],['plagiarism','الانتحال'],['organized','منظّم'],['improve','يُحسّن / يتحسّن'],['independently','بشكل مستقل'],['challenge','تحدٍّ'],['conflict','خلاف / نزاع'],['deal with','يتعامل مع'],['compromise','حل وسط'],['career','مسيرة مهنية'],['work placement','تدريب عملي في جهة عمل'],['contribute to','يُساهم في']];
const grid=document.querySelector('#glossary-grid'),search=document.querySelector('#glossary-search'),toggleArabic=document.querySelector('#toggle-arabic');let arabicVisible=true;
function renderGlossary(){const q=(search.value||'').trim().toLowerCase();const matches=glossary.filter(([en,ar])=>en.toLowerCase().includes(q)||ar.includes(q));grid.innerHTML=matches.map(([en,ar])=>`<article class="word-card ${arabicVisible?'':'hide-arabic'}"><strong>${en}</strong><span lang="ar" dir="rtl">${ar}</span></article>`).join('');document.querySelector('#empty-state').hidden=matches.length>0;}
search.addEventListener('input',renderGlossary);toggleArabic.addEventListener('click',()=>{arabicVisible=!arabicVisible;toggleArabic.textContent=arabicVisible?'Hide Arabic':'Show Arabic';toggleArabic.setAttribute('aria-pressed',arabicVisible);renderGlossary();});renderGlossary();
const boxes=[...document.querySelectorAll('.complete-box')],bar=document.querySelector('#progress-bar'),progressText=document.querySelector('#progress-text');
function loadProgress(){let saved=[];try{saved=JSON.parse(localStorage.getItem('interview-ready-progress')||'[]')}catch{}boxes.forEach((box,i)=>box.checked=!!saved[i]);updateProgress(false)}
function updateProgress(save=true){const state=boxes.map(b=>b.checked),done=state.filter(Boolean).length;bar.style.width=`${done/boxes.length*100}%`;progressText.textContent=`${done} of ${boxes.length} rooms completed`;boxes.forEach(b=>b.closest('.journey-card').classList.toggle('completed',b.checked));if(save)localStorage.setItem('interview-ready-progress',JSON.stringify(state));}
boxes.forEach(b=>b.addEventListener('change',()=>updateProgress()));document.querySelector('#reset-progress').addEventListener('click',()=>{boxes.forEach(b=>b.checked=false);updateProgress()});loadProgress();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const menuBtn=document.querySelector('.menu-button'),navLinks=document.querySelector('.nav-links');menuBtn.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
document.querySelector('.theme-button').addEventListener('click',e=>{const on=document.body.classList.toggle('alt-theme');e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.textContent=on?'◐':'☀'});
const back=document.querySelector('.back-top');window.addEventListener('scroll',()=>back.classList.toggle('show',scrollY>600),{passive:true});back.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));